# Generated by Django 4.2 on 2023-04-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='RequestingCar',
        ),
    ]
