# Generated by Django 4.2 on 2023-04-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_car_requestingcar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Ordershistory',
        ),
        migrations.RenameModel(
            old_name='RequestingCar',
            new_name='RequestingOrder',
        ),
    ]
