# Generated by Django 4.2 on 2023-04-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='def.jpeg', upload_to='photos/%y/%m/%d'),
        ),
    ]
