# Generated by Django 4.2 on 2023-04-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nation',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
